version: "3.9"

services:

  #################################################
  # MCP SERVER
  #################################################

  mcp-server:

    build:
      context: ..
      dockerfile: docker/Dockerfile.mcp

    image: chargeability-mcp:latest

    container_name: chargeability-mcp

    restart: unless-stopped

    env_file:
      - ../.env

    environment:
      MCP_PORT: 8000

    ports:
      - "8000:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - chargeability-network



  #################################################
  # FASTAPI AGENT
  #################################################

  fastapi:

    build:
      context: ..
      dockerfile: docker/Dockerfile.agent

    image: chargeability-fastapi-agent:latest

    container_name: chargeability-api

    restart: unless-stopped

    env_file:
      - ../.env

    environment:
      MCP_SERVER_URL: http://mcp-server:8000/mcp

    depends_on:
      - mcp-server

    ports:
      - "8080:8080"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - chargeability-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s


#################################################
# NETWORK
#################################################

networks:
  chargeability-network:
    driver: bridge