# -------------------------------------------------------
# Base Image
# -------------------------------------------------------
FROM python:3.12-slim

# -------------------------------------------------------
# Prevent Python from writing pyc files
# and enable real-time logging
# -------------------------------------------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# -------------------------------------------------------
# Working Directory
# -------------------------------------------------------
WORKDIR /app

# -------------------------------------------------------
# Install system packages
# -------------------------------------------------------
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------
# Install Python dependencies
# -------------------------------------------------------
COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# -------------------------------------------------------
# Copy project
# -------------------------------------------------------
COPY . .

# -------------------------------------------------------
# Expose MCP Port
# -------------------------------------------------------
EXPOSE 8000

# -------------------------------------------------------
# Start MCP Server
# -------------------------------------------------------
CMD ["python", "mcp_server.py"]